# docker/docker-compose.yaml

version: "3.8"

services:
  postgres:
    image: "postgres:latest"
    container_name: ch_postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "cinehub"
      POSTGRES_PASSWORD: "cinehub"
      POSTGRES_DB: "cinehub" 
    volumes: 
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  minio:
    image: "bitnami/minio:latest"
    container_name: ch_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root"
      MINIO_ROOT_PASSWORD: "password"
