spring:
  profiles:
    active: dev
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        validation-mode: none
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
    show-sql: false
  main:
    web-application-type: servlet

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: "/documentation"